name: geppetto_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"
    min_sdk_android: 21
    windows:
     generate: true
     image_path: "assets/icon/icon.png"
     icon_size: 48


flutter:
  uses-material-design: true

  assets:
    - assets/logo-gpto.svg
